before_script:
  - dnf -y install python-pep8 pylint python-nose python-argcomplete

basic-tests:
  script:
    - pep8 --show-source --show-pep8 setup.py planex tests
    - pylint setup.py planex
    - nosetests
